title: "tyche.cc"
languageCode: "zh-CN"
baseurl: "http://tyche.cc/"
copyright: "Copyright (c) 2016. All rights reserved."
theme: "hugo-hueman-theme"
MetaDataFormat: "yaml"
canonifyurls: false
builddrafts: false
PaginatePath: paginator
pygmentsStyle: "monokai"
pygmentsUseClasses: true
RSSUri: "feed.xml"
disablePathToLower: true
uglyURLs: false
hasCJKLanguage: true
ignoreFiles: [ "\\.bak$", "\\.old$" ]
permalinks:
  posts: /:year/:month/:day/:slug/
Taxonomies:
  tag: "tags"
  category: "categories"
params:
  CopyrightHTML: "Copyright &#xA9; 2016. All Rights Reserved."
  GitHubUser: "bihai"
  SidebarRecentLimit: 5
  DateForm : "2016年01月02日"
  Tagline: "tyche.cc"
  Description: "Tyche.cc Yields Confidence, Hope & Emotions."
  Keywords: "blog,basic,language,notes,share"
  Categories:
    - "心得笔记-blog"
    - "技术文章-article"
    - "灌水乐乐-post"
menu:
  home:
    - Name: "文章列表"
      Weight: 1
      Identifier: "post"
      URL: "/post/"
    - Name: "Gallery"
      Weight: 2
      Identifier: "gallery"
      URL: "/gallery/"
    - Name: "Project"
      Weight: 2
      Identifier: "project"
      URL: "/project/"
    - Name: "皮肤列表"
      Weight: 2
      Identifier: "theme"
      URL: "/theme/"
    - Name: "示例网站"
      Weight: 3
      Identifier: "showcase"
      URL: "/showcase/"
    - Name: "关于"
      Weight: 4
      Identifier: "donate"
      URL: "/about/"
  link:
    - Name: "官方GitHub"
      Weight: 1
      Identifier: "hugo-github"
      URL: "https://github.com/spf13/hugo"
    - Name: "本站GitHub"
      Weight: 2
      Identifier: "hugo-org-github"
      URL: "https://github.com/coderzh/gohugo.org"
  doclink:
    - Name: "英文文档"
      Weight: 1
      Identifier: "doc-en"
      URL: "https://gohugo.io/overview/introduction/"
    - Name: "中文文档"
      Weight: 2
      Identifier: "doc-cn"
      URL: "/doc/"
  main:
    - Name: "快速开始"
      Identifier: "getting started"
      Weight: -100
    - Name: "Hugo命令"
      Identifier: "commands"
      Weight: -95
      URL: "/doc/commands/"
    - Name: "内容(Content)"
      Identifier: "content"
      Weight: -90
    - Name: "皮肤(Themes)"
      Identifier: "themes"
      Weight: -85
    - Name: "模板(Templates)"
      Identifier: "layout"
      Weight: -80
    - Name: "分类(Taxonomies)"
      Identifier: "taxonomy"
      Weight: -70
    - Name: "其他"
      Identifier: "extras"
      Weight: -60
    - Name: "工具"
      Weight: -55
      URL: "/doc/tools/"
    - Name: "社区"
      Identifier: "community"
      Weight: -50
    - Name: "指南"
      Identifier: "tutorials"
      Weight: -40
    - Name: "讨论社区"
      Parent: "community"
      Weight: 150
      URL: "http://discuss.gohugo.io"
    - Name: "常见问题"
      Identifier: "troubleshooting"
      Weight: -30
         
author:
  name: "bihai"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
blackfriday:
  angledQuotes: true
  fractions: false
  plainIDAnchors: true
  extensions:
    - hardLineBreak